version: '3'
services:
  server:
    image: node:17-alpine
    container_name: highscore-server
    working_dir: /server
    volumes:
      - ./server:/server
    command: npm install && npm run start
    environment:
      PORT: '8080'
      dbStorage: 'highscore-db/storage.sqlite'
    ports:
      - '8080:8080'
    expose: 
      - '8080'
